### ISSUE TITLE
User Scaffold

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#570]
# Introduction

The `user` model is the core of vutuv. We have to import all the data of v1.1 to the new model and should try to clean it up as good as possible during the process of creating a v2.0 version. The import process will be dealt with in an extra issue.

## Authentication

Obviously the `user` model goes hand in hand with authentication. I think [phauxth](https://github.com/riverrun/phauxth) is a good library for Phoenix we can use. But I'm open for other solutions. We are not going to have a magic-link-only login procedure but a password first and if somebody doesn't want it magic-link second solution (for which we can use the phauxth password reset mechanism). So old users can still log in without a password.

# Attributes

- :first_name, :string
- :last_name, :string
- :middlename, :string
- :nickname, :string
- :honorific_prefix, :string
- :honorific_suffix, :string
- :gender, :string # male, female, other (not sure if other or diverse is a better fit)
- :birthday_day, :integer
- :birthday_month, :integer
- :birthday_year, :integer
- :locale, :string # de|en (currently)
- :verified, :boolean, default: false
- :avatar, Vutuv.Avatar.Type
- :active_slug, :string
- :headline, :string
- :noindex?, :boolean, default: false
- :validated?, :boolean, default: false
- :send_birthday_reminder, :boolean, default: true
- :password_digest/hash # other name also fine

## Validations

- There has to be a :first_name or a :last_name.
- There has to be a :gender # please check v1.1 for the values
- There has to be a :local [de|en]
- There has to be a :active_slug which has to be generated during the create.
- The birthday is a bit tricky. We want people to enter either their full birthday (including the year) or just the day and month (without the year) in case they don't want anybody to know how old they are. Validation has to cover this. But a birthday doesn't have to be entered.
- validate_length(:first_name, max: 80)
- validate_length(:last_name, max: 80)
- validate_length(:middlename, max: 80)
- validate_length(:nickname, max: 80)
- validate_length(:honorific_prefix, max: 80)
- validate_length(:honorific_suffix, max: 80)
- validate_length(:headline, max: 255)

## Questions/Problems

- In the old model we did not have an `email_address` field. It was separated in an extra model to have the possibility of several email addresses. I think this is still a valid approach but I'm not 100% sure any more. Feel free to include it here too if phauxth needs it. If we put `email_address` in this model we have to add a unique restrain in the validations. And email addresses should always be saved downcased.
- I'm not happy with the :send_birthday_reminder attribute because I feel this should be in an other model. A model with other sorts of triggers. Feel free to create an other model or just leave it as it is.
- We have to find a better solution for the old :administrator field. That was just a quick hack for v1.1 but that needs to be implemented better.
- Should we include https://github.com/izelnakri/paper_trail from the beginning of v2? Please do so if it is not too much work.
- Please double check the v1.1 users model if we forget something in this issue and add it to the issue if it makes sense.

# To-Dos
 
- [ ] Create the model/scaffold
- [ ] Create the validations
- [ ] Create a sign up page which will is the root_path if not logged in. If #558 is good at the time of implementation use it otherwise standard default CSS and HTML will do. We can make it pretty later.
- [ ] Create a user#show page which can be accessed by the :slug (e.g. /users/stefan.wintermeyer).
- [ ] Create a user#edit page which can be accessed and used by the user only.
- [ ] Disable user#index for now. I think we might need it in the future as some sort of partial but not now.

About CSS and usability:  No special CSS needed. We'll take care of that later.

**Comment by hendri-tobing** [comment]
I think it is better to let email_addresses separated from users, beside it can be many email_addresses, it has a different function with users, i.e: for authentication and communication. If we are using phauth we will also add other schema/model: authentication which will hold users hashed_password and sessions.

I also like the idea to separate send_birthday_reminder to other model/schema which will contain all scheduled/cron/quantum jobs, such as if we want to end user session after specific time inactivity, working anniversary, etc.

What is the purpose of administrator field?

**Comment by wintermeyer** [comment]
The administrator field was a cheap way of giving administrators special privileges. It was a quick hack so I could verify other users on the WebGUI. We need to solve this better in v2.0.

**Comment by riverrun** [comment]
Nearly everything in this issue has been completed. I think the only thing left here is to add the 'slug' functionality to the `user/show` page.
